[package]
name = "ecp"
version = "0.1.0"
authors = ["Curtis Maves <curtismaves@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
controller = ["rs_ws281x"]

[dependencies]
ham = { git="https://github.com/cmaves/ham", branch = "master" }




rs_ws281x = { version = "0.2.3", optional=true }


